version: "3.7"
services:
    gatsby:
        build:
            context: ./gatsby
            dockerfile: Dockerfile
        container_name: gatsby
        ports:
            - "8000:8000"
            - "9000:9000"
        volumes:
            - ./gatsby:/home/node
        environment:
            - NODE_ENV=development
        stdin_open: true
